export const mockData = {
  results: [
    {
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      dairyFree: true,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 25,
      gaps: 'no',
      preparationMinutes: -1,
      cookingMinutes: -1,
      aggregateLikes: 2,
      healthScore: 54,
      creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
      license: 'CC BY 3.0',
      sourceName: 'Foodista',
      pricePerServing: 496.7,
      extendedIngredients: [
        {
          id: 2048,
          aisle: 'Oil, Vinegar, Salad Dressing',
          image: 'apple-cider-vinegar.jpg',
          consistency: 'LIQUID',
          name: 'apple cider vinegar',
          nameClean: 'apple cider vinegar',
          original: '1/4 cup apple cider vinegar',
          originalName: 'apple cider vinegar',
          amount: 0.25,
          unit: 'cup',
          meta: [],
          measures: {
            us: {
              amount: 0.25,
              unitShort: 'cups',
              unitLong: 'cups',
            },
            metric: {
              amount: 59.147,
              unitShort: 'ml',
              unitLong: 'milliliters',
            },
          },
        },
        {
          id: 10958,
          aisle: 'Meat',
          image: 'pork-shoulder.png',
          consistency: 'SOLID',
          name: 'pork shoulder',
          nameClean: 'boneless pork shoulder',
          original:
            '3 pounds 1 boneless pork shoulder (Boston butt), about, excess fat removed, cut into chun',
          originalName:
            '1 boneless pork shoulder (Boston butt), about, excess fat removed, cut into chun',
          amount: 3.0,
          unit: 'pounds',
          meta: ['boneless', 'fat removed', 'cut into chun', '(Boston butt)'],
          measures: {
            us: {
              amount: 3.0,
              unitShort: 'lb',
              unitLong: 'pounds',
            },
            metric: {
              amount: 1.361,
              unitShort: 'kgs',
              unitLong: 'kgs',
            },
          },
        },
        {
          id: 93730,
          aisle: 'Baking',
          image: 'brioche-bun.jpg',
          consistency: 'SOLID',
          name: 'brioche rolls',
          nameClean: 'brioche',
          original: 'Brioche rolls, split',
          originalName: 'Brioche rolls, split',
          amount: 4.0,
          unit: 'servings',
          meta: ['split'],
          measures: {
            us: {
              amount: 4.0,
              unitShort: 'servings',
              unitLong: 'servings',
            },
            metric: {
              amount: 4.0,
              unitShort: 'servings',
              unitLong: 'servings',
            },
          },
        },
        {
          id: 2014,
          aisle: 'Spices and Seasonings',
          image: 'ground-cumin.jpg',
          consistency: 'SOLID',
          name: 'cumin seeds',
          nameClean: 'cumin seeds',
          original: '1/2 teaspoon cumin seeds',
          originalName: 'cumin seeds',
          amount: 0.5,
          unit: 'teaspoon',
          meta: [],
          measures: {
            us: {
              amount: 0.5,
              unitShort: 'tsps',
              unitLong: 'teaspoons',
            },
            metric: {
              amount: 0.5,
              unitShort: 'tsps',
              unitLong: 'teaspoons',
            },
          },
        },
        {
          id: 10019334,
          aisle: 'Baking',
          image: 'dark-brown-sugar.png',
          consistency: 'SOLID',
          name: 'brown sugar',
          nameClean: 'dark brown sugar',
          original: '2 tablespoons dark brown sugar',
          originalName: 'dark brown sugar',
          amount: 2.0,
          unit: 'tablespoons',
          meta: ['dark'],
          measures: {
            us: {
              amount: 2.0,
              unitShort: 'Tbsps',
              unitLong: 'Tbsps',
            },
            metric: {
              amount: 2.0,
              unitShort: 'Tbsps',
              unitLong: 'Tbsps',
            },
          },
        },
        {
          id: 2018,
          aisle: 'Spices and Seasonings',
          image: 'fennel-seeds.jpg',
          consistency: 'SOLID',
          name: 'fennel seeds',
          nameClean: 'fennel seeds',
          original: '1/2 teaspoon fennel seeds',
          originalName: 'fennel seeds',
          amount: 0.5,
          unit: 'teaspoon',
          meta: [],
          measures: {
            us: {
              amount: 0.5,
              unitShort: 'tsps',
              unitLong: 'teaspoons',
            },
            metric: {
              amount: 0.5,
              unitShort: 'tsps',
              unitLong: 'teaspoons',
            },
          },
        },
        {
          id: 11216,
          aisle: 'Produce;Ethnic Foods;Spices and Seasonings',
          image: 'ginger.png',
          consistency: 'SOLID',
          name: 'ginger',
          nameClean: 'ginger',
          original: '2 tablespoons minced ginger',
          originalName: 'minced ginger',
          amount: 2.0,
          unit: 'tablespoons',
          meta: ['minced'],
          measures: {
            us: {
              amount: 2.0,
              unitShort: 'Tbsps',
              unitLong: 'Tbsps',
            },
            metric: {
              amount: 2.0,
              unitShort: 'Tbsps',
              unitLong: 'Tbsps',
            },
          },
        },
        {
          id: 1082047,
          aisle: 'Spices and Seasonings',
          image: 'salt.jpg',
          consistency: 'SOLID',
          name: 'kosher salt',
          nameClean: 'kosher salt',
          original: 'Kosher salt',
          originalName: 'Kosher salt',
          amount: 4.0,
          unit: 'servings',
          meta: [],
          measures: {
            us: {
              amount: 4.0,
              unitShort: 'servings',
              unitLong: 'servings',
            },
            metric: {
              amount: 4.0,
              unitShort: 'servings',
              unitLong: 'servings',
            },
          },
        },
        {
          id: 9160,
          aisle: 'Produce',
          image: 'lime-juice.png',
          consistency: 'LIQUID',
          name: 'lime juice',
          nameClean: 'lime juice',
          original: '1/2 cup fresh lime juice',
          originalName: 'fresh lime juice',
          amount: 0.5,
          unit: 'cup',
          meta: ['fresh'],
          measures: {
            us: {
              amount: 0.5,
              unitShort: 'cups',
              unitLong: 'cups',
            },
            metric: {
              amount: 118.294,
              unitShort: 'ml',
              unitLong: 'milliliters',
            },
          },
        },
        {
          id: 1009176,
          aisle: 'Not in Grocery Store/Homemade',
          image: 'mango-puree.png',
          consistency: 'SOLID',
          name: 'mango puree',
          nameClean: 'mango puree',
          original: '2 cups mango puree',
          originalName: 'mango puree',
          amount: 2.0,
          unit: 'cups',
          meta: [],
          measures: {
            us: {
              amount: 2.0,
              unitShort: 'cups',
              unitLong: 'cups',
            },
            metric: {
              amount: 473.176,
              unitShort: 'ml',
              unitLong: 'milliliters',
            },
          },
        },
        {
          id: 19304,
          aisle: 'Baking',
          image: 'molasses.jpg',
          consistency: 'SOLID',
          name: 'molasses',
          nameClean: 'molasses',
          original: '2 tablespoons molasses',
          originalName: 'molasses',
          amount: 2.0,
          unit: 'tablespoons',
          meta: [],
          measures: {
            us: {
              amount: 2.0,
              unitShort: 'Tbsps',
              unitLong: 'Tbsps',
            },
            metric: {
              amount: 2.0,
              unitShort: 'Tbsps',
              unitLong: 'Tbsps',
            },
          },
        },
        {
          id: 11282,
          aisle: 'Produce',
          image: 'brown-onion.png',
          consistency: 'SOLID',
          name: 'onion',
          nameClean: 'onion',
          original: '1 onion, finely minced',
          originalName: 'onion, finely minced',
          amount: 1.0,
          unit: '',
          meta: ['finely minced'],
          measures: {
            us: {
              amount: 1.0,
              unitShort: '',
              unitLong: '',
            },
            metric: {
              amount: 1.0,
              unitShort: '',
              unitLong: '',
            },
          },
        },
        {
          id: 2028,
          aisle: 'Spices and Seasonings',
          image: 'paprika.jpg',
          consistency: 'SOLID',
          name: 'paprika',
          nameClean: 'paprika',
          original: '1 tablespoon paprika',
          originalName: 'paprika',
          amount: 1.0,
          unit: 'tablespoon',
          meta: [],
          measures: {
            us: {
              amount: 1.0,
              unitShort: 'Tbsp',
              unitLong: 'Tbsp',
            },
            metric: {
              amount: 1.0,
              unitShort: 'Tbsp',
              unitLong: 'Tbsp',
            },
          },
        },
        {
          id: 11977,
          aisle: 'Produce',
          image: 'serrano-pepper.jpg',
          consistency: 'SOLID',
          name: 'serrano pepper',
          nameClean: 'serrano pepper',
          original:
            "1 serrano pepper, thinly sliced (seeds discarded if you don't like it spicy)",
          originalName:
            "serrano pepper, thinly sliced (seeds discarded if you don't like it spicy)",
          amount: 1.0,
          unit: '',
          meta: [
            'thinly sliced',
            "(seeds discarded if you don't like it spicy)",
          ],
          measures: {
            us: {
              amount: 1.0,
              unitShort: '',
              unitLong: '',
            },
            metric: {
              amount: 1.0,
              unitShort: '',
              unitLong: '',
            },
          },
        },
        {
          id: 4669,
          aisle: 'Oil, Vinegar, Salad Dressing',
          image: 'vegetable-oil.jpg',
          consistency: 'LIQUID',
          name: 'vegetable oil',
          nameClean: 'vegetable oil',
          original: '1/4 cup vegetable oil',
          originalName: 'vegetable oil',
          amount: 0.25,
          unit: 'cup',
          meta: [],
          measures: {
            us: {
              amount: 0.25,
              unitShort: 'cups',
              unitLong: 'cups',
            },
            metric: {
              amount: 59.147,
              unitShort: 'ml',
              unitLong: 'milliliters',
            },
          },
        },
        {
          id: 6971,
          aisle: 'Condiments',
          image: 'dark-sauce.jpg',
          consistency: 'LIQUID',
          name: 'worcestershire sauce',
          nameClean: 'worcestershire sauce',
          original: '1/4 cup Worcestershire sauce',
          originalName: 'Worcestershire sauce',
          amount: 0.25,
          unit: 'cup',
          meta: [],
          measures: {
            us: {
              amount: 0.25,
              unitShort: 'cups',
              unitLong: 'cups',
            },
            metric: {
              amount: 59.147,
              unitShort: 'ml',
              unitLong: 'milliliters',
            },
          },
        },
      ],
      id: 657226,
      title: 'Pulled Pork Sandwich with Mango BBQ sauce',
      readyInMinutes: 45,
      servings: 4,
      sourceUrl:
        'http://www.foodista.com/recipe/TV32HN3D/pulled-pork-sandwich-with-mango-bbq-sauce',
      image: 'https://spoonacular.com/recipeImages/657226-312x231.jpg',
      imageType: 'jpg',
      summary:
        'Pulled Pork Sandwich with Mango BBQ sauce might be just the <b>American</b> recipe you are searching for. One portion of this dish contains roughly <b>83g of protein</b>, <b>34g of fat</b>, and a total of <b>876 calories</b>. For <b>$4.97 per serving</b>, this recipe <b>covers 48%</b> of your daily requirements of vitamins and minerals. This recipe serves 4. This recipe from Foodista has 2 fans. Not a lot of people really liked this main course. From preparation to the plate, this recipe takes about <b>45 minutes</b>. If you have fennel seeds, brown sugar, cumin seeds, and a few other ingredients on hand, you can make it. It is a good option if you\'re following a <b>dairy free</b> diet. Taking all factors into account, this recipe <b>earns a spoonacular score of 83%</b>, which is tremendous. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/pulled-pork-sandwich-with-mango-bbq-sauce-1343309">Pulled Pork Sandwich with Mango BBQ sauce</a>, <a href="https://spoonacular.com/recipes/pulled-pork-with-mango-bbq-sauce-320309">Pulled Pork with Mango BBQ Sauce</a>, and <a href="https://spoonacular.com/recipes/pulled-pork-sandwich-with-white-bbq-sauce-9-points-1292953">Pulled Pork Sandwich with White BBQ Sauce – 9 Points</a>.',
      cuisines: ['American'],
      dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
      diets: ['dairy free'],
      occasions: [],
      analyzedInstructions: [
        {
          name: 'Rub',
          steps: [
            {
              number: 1,
              step: 'Combine the rub ingredients, in a small bowl and massage it into the pork shoulder until well coated. Set aside while you make BBQ sauce. You could do this a day ahead and keep refrigerated until ready to use.BBQ sauce: In a large saucepan, warm the oil, over low heat, until hot and shimmering.',
              ingredients: [
                {
                  id: 10072,
                  name: 'pork shoulder',
                  localizedName: 'pork shoulder',
                  image: 'pork-shoulder.png',
                },
                {
                  id: 6150,
                  name: 'barbecue sauce',
                  localizedName: 'barbecue sauce',
                  image: 'barbecue-sauce.jpg',
                },
                {
                  id: 4582,
                  name: 'cooking oil',
                  localizedName: 'cooking oil',
                  image: 'vegetable-oil.jpg',
                },
                {
                  id: 1012034,
                  name: 'dry seasoning rub',
                  localizedName: 'dry seasoning rub',
                  image: 'seasoning.png',
                },
              ],
              equipment: [
                {
                  id: 404669,
                  name: 'sauce pan',
                  localizedName: 'sauce pan',
                  image: 'sauce-pan.jpg',
                },
                {
                  id: 404783,
                  name: 'bowl',
                  localizedName: 'bowl',
                  image: 'bowl.jpg',
                },
              ],
            },
            {
              number: 2,
              step: 'Add the cumin and fennel; they should splutter upon contact - be careful! Once the spluttering subsides, add the onions, ginger and serrano and a little salt, to taste.',
              ingredients: [
                {
                  id: 11957,
                  name: 'fennel',
                  localizedName: 'fennel',
                  image: 'fennel.png',
                },
                {
                  id: 11216,
                  name: 'ginger',
                  localizedName: 'ginger',
                  image: 'ginger.png',
                },
                {
                  id: 11282,
                  name: 'onion',
                  localizedName: 'onion',
                  image: 'brown-onion.png',
                },
                {
                  id: 1002014,
                  name: 'cumin',
                  localizedName: 'cumin',
                  image: 'ground-cumin.jpg',
                },
                {
                  id: 2047,
                  name: 'salt',
                  localizedName: 'salt',
                  image: 'salt.jpg',
                },
              ],
              equipment: [],
            },
            {
              number: 3,
              step: "Saute until they soften but don't let them get any color.",
              ingredients: [],
              equipment: [],
            },
            {
              number: 4,
              step: 'Add the rest of the sauce ingredients. Simmer about 5 minutes. Taste and season.',
              ingredients: [
                {
                  id: 0,
                  name: 'sauce',
                  localizedName: 'sauce',
                  image: '',
                },
              ],
              equipment: [],
              length: {
                number: 5,
                unit: 'minutes',
              },
            },
            {
              number: 5,
              step: 'Add the pork shoulder to the saucepan, coating it with the sauce. Cover, and gently simmer until the pork falls apart easily, stirring and turning often, about 3 hours.',
              ingredients: [
                {
                  id: 10072,
                  name: 'pork shoulder',
                  localizedName: 'pork shoulder',
                  image: 'pork-shoulder.png',
                },
                {
                  id: 0,
                  name: 'sauce',
                  localizedName: 'sauce',
                  image: '',
                },
                {
                  id: 10010219,
                  name: 'pork',
                  localizedName: 'pork',
                  image: 'pork-tenderloin-raw.png',
                },
              ],
              equipment: [
                {
                  id: 404669,
                  name: 'sauce pan',
                  localizedName: 'sauce pan',
                  image: 'sauce-pan.jpg',
                },
              ],
              length: {
                number: 180,
                unit: 'minutes',
              },
            },
            {
              number: 6,
              step: "Remove the pork from the saucepan and shred it using 2 forks. Return it to the sauce and stir to coat with the sauce. Put a generous spoonful of the pork inside a brioche bun, top with a few slices of pickle and serve. Aarti's Note: prepare to have your loved one swoon over you!",
              ingredients: [
                {
                  id: 10093730,
                  name: 'brioche bun',
                  localizedName: 'brioche bun',
                  image: 'brioche-bun.jpg',
                },
                {
                  id: 11937,
                  name: 'pickles',
                  localizedName: 'pickles',
                  image: 'dill-pickles.jpg',
                },
                {
                  id: 0,
                  name: 'sauce',
                  localizedName: 'sauce',
                  image: '',
                },
                {
                  id: 10010219,
                  name: 'pork',
                  localizedName: 'pork',
                  image: 'pork-tenderloin-raw.png',
                },
              ],
              equipment: [
                {
                  id: 404669,
                  name: 'sauce pan',
                  localizedName: 'sauce pan',
                  image: 'sauce-pan.jpg',
                },
              ],
            },
          ],
        },
      ],
      spoonacularSourceUrl:
        'https://spoonacular.com/pulled-pork-sandwich-with-mango-bbq-sauce-657226',
      usedIngredientCount: 0,
      missedIngredientCount: 13,
      missedIngredients: [
        {
          id: 2048,
          amount: 0.25,
          unit: 'cup',
          unitLong: 'cups',
          unitShort: 'cup',
          aisle: 'Oil, Vinegar, Salad Dressing',
          name: 'apple cider vinegar',
          original: '1/4 cup apple cider vinegar',
          originalName: 'apple cider vinegar',
          meta: [],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/apple-cider-vinegar.jpg',
        },
        {
          id: 10958,
          amount: 3.0,
          unit: 'pounds',
          unitLong: 'pounds',
          unitShort: 'lb',
          aisle: 'Meat',
          name: 'pork shoulder',
          original:
            '3 pounds 1 boneless pork shoulder (Boston butt), about, excess fat removed, cut into chun',
          originalName:
            '1 boneless pork shoulder (Boston butt), about, excess fat removed, cut into chun',
          meta: ['boneless', 'fat removed', 'cut into chun', '(Boston butt)'],
          extendedName: 'lean boneless pork shoulder',
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/pork-shoulder.png',
        },
        {
          id: 93730,
          amount: 4.0,
          unit: 'servings',
          unitLong: 'servings',
          unitShort: 'servings',
          aisle: 'Baking',
          name: 'brioche rolls',
          original: 'Brioche rolls, split',
          originalName: 'Brioche rolls, split',
          meta: ['split'],
          extendedName: 'split brioche rolls',
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/brioche-bun.jpg',
        },
        {
          id: 2014,
          amount: 0.5,
          unit: 'teaspoon',
          unitLong: 'teaspoons',
          unitShort: 'tsp',
          aisle: 'Spices and Seasonings',
          name: 'cumin seeds',
          original: '1/2 teaspoon cumin seeds',
          originalName: 'cumin seeds',
          meta: [],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/ground-cumin.jpg',
        },
        {
          id: 2018,
          amount: 0.5,
          unit: 'teaspoon',
          unitLong: 'teaspoons',
          unitShort: 'tsp',
          aisle: 'Spices and Seasonings',
          name: 'fennel seeds',
          original: '1/2 teaspoon fennel seeds',
          originalName: 'fennel seeds',
          meta: [],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/fennel-seeds.jpg',
        },
        {
          id: 11216,
          amount: 2.0,
          unit: 'tablespoons',
          unitLong: 'tablespoons',
          unitShort: 'Tbsp',
          aisle: 'Produce;Ethnic Foods;Spices and Seasonings',
          name: 'ginger',
          original: '2 tablespoons minced ginger',
          originalName: 'minced ginger',
          meta: ['minced'],
          image: 'https://spoonacular.com/cdn/ingredients_100x100/ginger.png',
        },
        {
          id: 9160,
          amount: 0.5,
          unit: 'cup',
          unitLong: 'cups',
          unitShort: 'cup',
          aisle: 'Produce',
          name: 'lime juice',
          original: '1/2 cup fresh lime juice',
          originalName: 'fresh lime juice',
          meta: ['fresh'],
          extendedName: 'fresh lime juice',
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/lime-juice.png',
        },
        {
          id: 1009176,
          amount: 2.0,
          unit: 'cups',
          unitLong: 'cups',
          unitShort: 'cup',
          aisle: 'Not in Grocery Store/Homemade',
          name: 'mango puree',
          original: '2 cups mango puree',
          originalName: 'mango puree',
          meta: [],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/mango-puree.png',
        },
        {
          id: 19304,
          amount: 2.0,
          unit: 'tablespoons',
          unitLong: 'tablespoons',
          unitShort: 'Tbsp',
          aisle: 'Baking',
          name: 'molasses',
          original: '2 tablespoons molasses',
          originalName: 'molasses',
          meta: [],
          image: 'https://spoonacular.com/cdn/ingredients_100x100/molasses.jpg',
        },
        {
          id: 11282,
          amount: 1.0,
          unit: '',
          unitLong: '',
          unitShort: '',
          aisle: 'Produce',
          name: 'onion',
          original: '1 onion, finely minced',
          originalName: 'onion, finely minced',
          meta: ['finely minced'],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/brown-onion.png',
        },
        {
          id: 2028,
          amount: 1.0,
          unit: 'tablespoon',
          unitLong: 'tablespoon',
          unitShort: 'Tbsp',
          aisle: 'Spices and Seasonings',
          name: 'paprika',
          original: '1 tablespoon paprika',
          originalName: 'paprika',
          meta: [],
          image: 'https://spoonacular.com/cdn/ingredients_100x100/paprika.jpg',
        },
        {
          id: 11977,
          amount: 1.0,
          unit: '',
          unitLong: '',
          unitShort: '',
          aisle: 'Produce',
          name: 'serrano pepper',
          original:
            "1 serrano pepper, thinly sliced (seeds discarded if you don't like it spicy)",
          originalName:
            "serrano pepper, thinly sliced (seeds discarded if you don't like it spicy)",
          meta: [
            'thinly sliced',
            "(seeds discarded if you don't like it spicy)",
          ],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/serrano-pepper.jpg',
        },
        {
          id: 6971,
          amount: 0.25,
          unit: 'cup',
          unitLong: 'cups',
          unitShort: 'cup',
          aisle: 'Condiments',
          name: 'worcestershire sauce',
          original: '1/4 cup Worcestershire sauce',
          originalName: 'Worcestershire sauce',
          meta: [],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/dark-sauce.jpg',
        },
      ],
      likes: 0,
      usedIngredients: [],
      unusedIngredients: [],
    },
    {
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      dairyFree: false,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 18,
      gaps: 'no',
      preparationMinutes: -1,
      cookingMinutes: -1,
      aggregateLikes: 1,
      healthScore: 10,
      creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
      license: 'CC BY 3.0',
      sourceName: 'Foodista',
      pricePerServing: 261.86,
      extendedIngredients: [
        {
          id: 1145,
          aisle: 'Milk, Eggs, Other Dairy',
          image: 'butter-sliced.jpg',
          consistency: 'SOLID',
          name: 'butter',
          nameClean: 'unsalted butter',
          original: '1 T. unsalted butter',
          originalName: 'unsalted butter',
          amount: 1.0,
          unit: 'T',
          meta: ['unsalted'],
          measures: {
            us: {
              amount: 1.0,
              unitShort: 'Tbsp',
              unitLong: 'Tbsp',
            },
            metric: {
              amount: 1.0,
              unitShort: 'Tbsp',
              unitLong: 'Tbsp',
            },
          },
        },
        {
          id: 10862,
          aisle: 'Meat',
          image: 'cooked-bacon.jpg',
          consistency: 'SOLID',
          name: 'bacon',
          nameClean: 'cooked bacon',
          original: '4 slices of bacon, cooked crisp and crumbled',
          originalName: 'bacon, cooked crisp and crumbled',
          amount: 4.0,
          unit: 'slices',
          meta: ['crumbled', 'crisp', 'cooked'],
          measures: {
            us: {
              amount: 4.0,
              unitShort: 'slice',
              unitLong: 'slices',
            },
            metric: {
              amount: 4.0,
              unitShort: 'slice',
              unitLong: 'slices',
            },
          },
        },
        {
          id: 1001009,
          aisle: 'Cheese',
          image: 'shredded-cheddar.jpg',
          consistency: 'SOLID',
          name: 'cheddar cheese',
          nameClean: 'shredded cheddar cheese',
          original: '1/2 c. finely shredded cheddar cheese',
          originalName: 'finely shredded cheddar cheese',
          amount: 0.5,
          unit: 'c',
          meta: ['shredded', 'finely'],
          measures: {
            us: {
              amount: 0.5,
              unitShort: 'cups',
              unitLong: 'cups',
            },
            metric: {
              amount: 118.294,
              unitShort: 'ml',
              unitLong: 'milliliters',
            },
          },
        },
        {
          id: 11291,
          aisle: 'Produce',
          image: 'spring-onions.jpg',
          consistency: 'SOLID',
          name: 'scallions',
          nameClean: 'spring onions',
          original: '2 medium scallions, thinly sliced',
          originalName: 'scallions, thinly sliced',
          amount: 2.0,
          unit: 'medium',
          meta: ['thinly sliced'],
          measures: {
            us: {
              amount: 2.0,
              unitShort: 'medium',
              unitLong: 'mediums',
            },
            metric: {
              amount: 2.0,
              unitShort: 'medium',
              unitLong: 'mediums',
            },
          },
        },
        {
          id: 1123,
          aisle: 'Milk, Eggs, Other Dairy',
          image: 'egg.png',
          consistency: 'SOLID',
          name: 'eggs',
          nameClean: 'egg',
          original: '6 eggs, lightly beaten',
          originalName: 'eggs, lightly beaten',
          amount: 6.0,
          unit: '',
          meta: ['lightly beaten'],
          measures: {
            us: {
              amount: 6.0,
              unitShort: '',
              unitLong: '',
            },
            metric: {
              amount: 6.0,
              unitShort: '',
              unitLong: '',
            },
          },
        },
        {
          id: 1102047,
          aisle: 'Spices and Seasonings',
          image: 'salt-and-pepper.jpg',
          consistency: 'SOLID',
          name: 'salt & pepper',
          nameClean: 'salt and pepper',
          original: 'salt & pepper',
          originalName: 'salt & pepper',
          amount: 4.0,
          unit: 'servings',
          meta: [],
          measures: {
            us: {
              amount: 4.0,
              unitShort: 'servings',
              unitLong: 'servings',
            },
            metric: {
              amount: 4.0,
              unitShort: 'servings',
              unitLong: 'servings',
            },
          },
        },
        {
          id: 6164,
          aisle: 'Pasta and Rice;Ethnic Foods',
          image: 'salsa.png',
          consistency: 'SOLID',
          name: 'chunky salsa',
          nameClean: 'salsa',
          original: '1/2 c. chunky salsa, drained of excess liquid',
          originalName: 'chunky salsa, drained of excess liquid',
          amount: 0.5,
          unit: 'c',
          meta: ['drained'],
          measures: {
            us: {
              amount: 0.5,
              unitShort: 'cups',
              unitLong: 'cups',
            },
            metric: {
              amount: 118.294,
              unitShort: 'ml',
              unitLong: 'milliliters',
            },
          },
        },
        {
          id: 93699,
          aisle: 'Bakery/Bread',
          image: 'ciabatta-roll.png',
          consistency: 'SOLID',
          name: 'ciabatta sandwich rolls',
          nameClean: 'ciabatta roll',
          original:
            '6 soft ciabatta sandwich rolls, split, toasted and buttered',
          originalName:
            'soft ciabatta sandwich rolls, split, toasted and buttered',
          amount: 6.0,
          unit: '',
          meta: ['split', 'soft', 'toasted'],
          measures: {
            us: {
              amount: 6.0,
              unitShort: '',
              unitLong: '',
            },
            metric: {
              amount: 6.0,
              unitShort: '',
              unitLong: '',
            },
          },
        },
        {
          id: 9037,
          aisle: 'Produce',
          image: 'avocado.jpg',
          consistency: 'SOLID',
          name: 'avocado',
          nameClean: 'avocado',
          original: 'sliced avocado',
          originalName: 'sliced avocado',
          amount: 4.0,
          unit: 'servings',
          meta: ['sliced'],
          measures: {
            us: {
              amount: 4.0,
              unitShort: 'servings',
              unitLong: 'servings',
            },
            metric: {
              amount: 4.0,
              unitShort: 'servings',
              unitLong: 'servings',
            },
          },
        },
      ],
      id: 643861,
      title: 'Frittata "Brinner" Sandwiches - Southwest Style',
      readyInMinutes: 45,
      servings: 4,
      sourceUrl:
        'https://www.foodista.com/recipe/FBQMTFXX/frittata-brinner-sandwiches-southwest-style',
      image: 'https://spoonacular.com/recipeImages/643861-312x231.jpg',
      imageType: 'jpg',
      summary:
        'Frittata "Brinner" Sandwiches - Southwest Style is a main course that serves 4. One serving contains <b>579 calories</b>, <b>24g of protein</b>, and <b>32g of fat</b>. For <b>$2.62 per serving</b>, this recipe <b>covers 20%</b> of your daily requirements of vitamins and minerals. 1 person found this recipe to be scrumptious and satisfying. This recipe from Foodista requires ciabatta sandwich rolls, bacon, cheddar cheese, and salt & pepper. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. Overall, this recipe earns a <b>solid spoonacular score of 50%</b>. Try <a href="https://spoonacular.com/recipes/southwest-steak-frittata-532220">Southwest Steak Frittata</a>, <a href="https://spoonacular.com/recipes/southwest-frittata-with-chicken-532563">Southwest Frittata with Chicken</a>, and <a href="https://spoonacular.com/recipes/baked-southwest-sandwiches-417103">Baked Southwest Sandwiches</a> for similar recipes.',
      cuisines: [],
      dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
      diets: [],
      occasions: [],
      analyzedInstructions: [
        {
          name: '',
          steps: [
            {
              number: 1,
              step: 'Preheat oven to 350 degrees f. In a small bowl combine the crumbled bacon, cheese and scallion, set aside. Season the beaten eggs with a little salt & pepper.  Melt butter in a 10-inch oven safe nonstick skillet over medium heat until the butter melts and the foaming subsides.',
              ingredients: [
                {
                  id: 99229,
                  name: 'real bacon pieces',
                  localizedName: 'real bacon pieces',
                  image: 'bacon-bits.jpg',
                },
                {
                  id: 1102047,
                  name: 'salt and pepper',
                  localizedName: 'salt and pepper',
                  image: 'salt-and-pepper.jpg',
                },
                {
                  id: 11291,
                  name: 'green onions',
                  localizedName: 'green onions',
                  image: 'spring-onions.jpg',
                },
                {
                  id: 1001,
                  name: 'butter',
                  localizedName: 'butter',
                  image: 'butter-sliced.jpg',
                },
                {
                  id: 1041009,
                  name: 'cheese',
                  localizedName: 'cheese',
                  image: 'cheddar-cheese.png',
                },
                {
                  id: 1123,
                  name: 'egg',
                  localizedName: 'egg',
                  image: 'egg.png',
                },
              ],
              equipment: [
                {
                  id: 404645,
                  name: 'frying pan',
                  localizedName: 'frying pan',
                  image: 'pan.png',
                },
                {
                  id: 404783,
                  name: 'bowl',
                  localizedName: 'bowl',
                  image: 'bowl.jpg',
                },
                {
                  id: 404784,
                  name: 'oven',
                  localizedName: 'oven',
                  image: 'oven.jpg',
                  temperature: {
                    number: 350.0,
                    unit: 'Fahrenheit',
                  },
                },
              ],
            },
            {
              number: 2,
              step: 'Add the eggs to the skillet and immediately sprinkle the bacon-cheese mixture over the top, spoon the drained salsa evenly over the top. Using a heat-proof spatula mix the frittata in small circular motions until the egg begins to set up into soft curds. Continue to cook, running the spatula around the edges of the frittata and lifting, letting the uncooked egg flow to the outer edges. (All this should take only a couple of minutes, start to finish.) When the frittata is mostly set with just the top looking a little runny, place the fritatta in the oven to finish cooking, about 3 minutes or so. Slide the frittata out onto a cutting board and cut into wedges for serving.',
              ingredients: [
                {
                  id: 1041009,
                  name: 'cheese',
                  localizedName: 'cheese',
                  image: 'cheddar-cheese.png',
                },
                {
                  id: 10123,
                  name: 'bacon',
                  localizedName: 'bacon',
                  image: 'raw-bacon.png',
                },
                {
                  id: 6164,
                  name: 'salsa',
                  localizedName: 'salsa',
                  image: 'salsa.png',
                },
                {
                  id: 1123,
                  name: 'egg',
                  localizedName: 'egg',
                  image: 'egg.png',
                },
              ],
              equipment: [
                {
                  id: 404716,
                  name: 'cutting board',
                  localizedName: 'cutting board',
                  image: 'cutting-board.jpg',
                },
                {
                  id: 404645,
                  name: 'frying pan',
                  localizedName: 'frying pan',
                  image: 'pan.png',
                },
                {
                  id: 404642,
                  name: 'spatula',
                  localizedName: 'spatula',
                  image: 'spatula-or-turner.jpg',
                },
                {
                  id: 404784,
                  name: 'oven',
                  localizedName: 'oven',
                  image: 'oven.jpg',
                },
              ],
              length: {
                number: 3,
                unit: 'minutes',
              },
            },
            {
              number: 3,
              step: 'Add the frittata wedges and sliced avocado to the toasted rolls.',
              ingredients: [
                {
                  id: 9037,
                  name: 'avocado',
                  localizedName: 'avocado',
                  image: 'avocado.jpg',
                },
                {
                  id: 0,
                  name: 'roll',
                  localizedName: 'roll',
                  image: 'dinner-yeast-rolls.jpg',
                },
              ],
              equipment: [],
            },
            {
              number: 4,
              step: 'Serve.',
              ingredients: [],
              equipment: [],
            },
          ],
        },
      ],
      spoonacularSourceUrl:
        'https://spoonacular.com/frittata-brinner-sandwiches-southwest-style-643861',
      usedIngredientCount: 0,
      missedIngredientCount: 8,
      missedIngredients: [
        {
          id: 1145,
          amount: 1.0,
          unit: 'T',
          unitLong: 'tablespoon',
          unitShort: 'Tbsp',
          aisle: 'Milk, Eggs, Other Dairy',
          name: 'butter',
          original: '1 T. unsalted butter',
          originalName: 'unsalted butter',
          meta: ['unsalted'],
          extendedName: 'unsalted butter',
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/butter-sliced.jpg',
        },
        {
          id: 10862,
          amount: 4.0,
          unit: 'slices',
          unitLong: 'slices',
          unitShort: 'slice',
          aisle: 'Meat',
          name: 'bacon',
          original: '4 slices of bacon, cooked crisp and crumbled',
          originalName: 'bacon, cooked crisp and crumbled',
          meta: ['crumbled', 'crisp', 'cooked'],
          extendedName: 'cooked bacon',
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/cooked-bacon.jpg',
        },
        {
          id: 1001009,
          amount: 0.5,
          unit: 'c',
          unitLong: 'cups',
          unitShort: 'cup',
          aisle: 'Cheese',
          name: 'cheddar cheese',
          original: '1/2 c. finely shredded cheddar cheese',
          originalName: 'finely shredded cheddar cheese',
          meta: ['shredded', 'finely'],
          extendedName: 'shredded cheddar cheese',
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/shredded-cheddar.jpg',
        },
        {
          id: 11291,
          amount: 2.0,
          unit: 'medium',
          unitLong: 'mediums',
          unitShort: 'medium',
          aisle: 'Produce',
          name: 'scallions',
          original: '2 medium scallions, thinly sliced',
          originalName: 'scallions, thinly sliced',
          meta: ['thinly sliced'],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/spring-onions.jpg',
        },
        {
          id: 1123,
          amount: 6.0,
          unit: '',
          unitLong: '',
          unitShort: '',
          aisle: 'Milk, Eggs, Other Dairy',
          name: 'eggs',
          original: '6 eggs, lightly beaten',
          originalName: 'eggs, lightly beaten',
          meta: ['lightly beaten'],
          image: 'https://spoonacular.com/cdn/ingredients_100x100/egg.png',
        },
        {
          id: 6164,
          amount: 0.5,
          unit: 'c',
          unitLong: 'cups',
          unitShort: 'cup',
          aisle: 'Pasta and Rice;Ethnic Foods',
          name: 'chunky salsa',
          original: '1/2 c. chunky salsa, drained of excess liquid',
          originalName: 'chunky salsa, drained of excess liquid',
          meta: ['drained'],
          image: 'https://spoonacular.com/cdn/ingredients_100x100/salsa.png',
        },
        {
          id: 93699,
          amount: 6.0,
          unit: '',
          unitLong: '',
          unitShort: '',
          aisle: 'Bakery/Bread',
          name: 'ciabatta sandwich rolls',
          original:
            '6 soft ciabatta sandwich rolls, split, toasted and buttered',
          originalName:
            'soft ciabatta sandwich rolls, split, toasted and buttered',
          meta: ['split', 'soft', 'toasted'],
          extendedName: 'split ciabatta sandwich rolls',
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/ciabatta-roll.png',
        },
        {
          id: 9037,
          amount: 4.0,
          unit: 'servings',
          unitLong: 'servings',
          unitShort: 'servings',
          aisle: 'Produce',
          name: 'avocado',
          original: 'sliced avocado',
          originalName: 'sliced avocado',
          meta: ['sliced'],
          image: 'https://spoonacular.com/cdn/ingredients_100x100/avocado.jpg',
        },
      ],
      likes: 0,
      usedIngredients: [],
      unusedIngredients: [],
    },
    {
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      dairyFree: true,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 29,
      gaps: 'no',
      preparationMinutes: -1,
      cookingMinutes: -1,
      aggregateLikes: 5,
      healthScore: 14,
      creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
      license: 'CC BY 3.0',
      sourceName: 'Foodista',
      pricePerServing: 271.49,
      extendedIngredients: [
        {
          id: 10123,
          aisle: 'Meat',
          image: 'raw-bacon.png',
          consistency: 'SOLID',
          name: 'bacon',
          nameClean: 'applewood smoked bacon',
          original: '6 strips bacon',
          originalName: 'bacon',
          amount: 6.0,
          unit: 'strips',
          meta: [],
          measures: {
            us: {
              amount: 6.0,
              unitShort: 'strips',
              unitLong: 'strips',
            },
            metric: {
              amount: 6.0,
              unitShort: 'strips',
              unitLong: 'strips',
            },
          },
        },
        {
          id: 13786,
          aisle: 'Meat',
          image: 'beef-chuck-roast.png',
          consistency: 'SOLID',
          name: 'beef chuck',
          nameClean: 'beef chuck roast',
          original: '2 pounds beef chuck',
          originalName: 'beef chuck',
          amount: 2.0,
          unit: 'pounds',
          meta: [],
          measures: {
            us: {
              amount: 2.0,
              unitShort: 'lb',
              unitLong: 'pounds',
            },
            metric: {
              amount: 907.185,
              unitShort: 'g',
              unitLong: 'grams',
            },
          },
        },
        {
          id: 4053,
          aisle: 'Oil, Vinegar, Salad Dressing',
          image: 'olive-oil.jpg',
          consistency: 'LIQUID',
          name: 'olive oil',
          nameClean: 'olive oil',
          original: '2 tablespoons olive oil',
          originalName: 'olive oil',
          amount: 2.0,
          unit: 'tablespoons',
          meta: [],
          measures: {
            us: {
              amount: 2.0,
              unitShort: 'Tbsps',
              unitLong: 'Tbsps',
            },
            metric: {
              amount: 2.0,
              unitShort: 'Tbsps',
              unitLong: 'Tbsps',
            },
          },
        },
        {
          id: 19334,
          aisle: 'Baking',
          image: 'light-brown-sugar.jpg',
          consistency: 'SOLID',
          name: 'brown sugar',
          nameClean: 'golden brown sugar',
          original: '1/2 cup brown sugar',
          originalName: 'brown sugar',
          amount: 0.5,
          unit: 'cup',
          meta: [],
          measures: {
            us: {
              amount: 0.5,
              unitShort: 'cups',
              unitLong: 'cups',
            },
            metric: {
              amount: 118.294,
              unitShort: 'ml',
              unitLong: 'milliliters',
            },
          },
        },
        {
          id: 1102047,
          aisle: 'Spices and Seasonings',
          image: 'salt-and-pepper.jpg',
          consistency: 'SOLID',
          name: 'salt and pepper',
          nameClean: 'salt and pepper',
          original: 'salt and pepper',
          originalName: 'salt and pepper',
          amount: 6.0,
          unit: 'servings',
          meta: [],
          measures: {
            us: {
              amount: 6.0,
              unitShort: 'servings',
              unitLong: 'servings',
            },
            metric: {
              amount: 6.0,
              unitShort: 'servings',
              unitLong: 'servings',
            },
          },
        },
        {
          id: 11282,
          aisle: 'Produce',
          image: 'brown-onion.png',
          consistency: 'SOLID',
          name: 'onion',
          nameClean: 'onion',
          original: '1 onion, chopped',
          originalName: 'onion, chopped',
          amount: 1.0,
          unit: '',
          meta: ['chopped'],
          measures: {
            us: {
              amount: 1.0,
              unitShort: '',
              unitLong: '',
            },
            metric: {
              amount: 1.0,
              unitShort: '',
              unitLong: '',
            },
          },
        },
        {
          id: 6150,
          aisle: 'Condiments',
          image: 'barbecue-sauce.jpg',
          consistency: 'SOLID',
          name: 'to 3 of barbecue sauce',
          nameClean: 'barbecue sauce',
          original: '2 cups to 3 of barbecue sauce',
          originalName: 'to 3 of barbecue sauce',
          amount: 2.0,
          unit: 'cups',
          meta: [],
          measures: {
            us: {
              amount: 2.0,
              unitShort: 'cups',
              unitLong: 'cups',
            },
            metric: {
              amount: 473.176,
              unitShort: 'ml',
              unitLong: 'milliliters',
            },
          },
        },
        {
          id: 18350,
          aisle: 'Bakery/Bread',
          image: 'hamburger-bun.jpg',
          consistency: 'SOLID',
          name: 'hawaiian rolls',
          nameClean: 'hamburger bun',
          original: 'Hamburger buns or Hawaiian rolls',
          originalName: 'Hamburger buns or Hawaiian rolls',
          amount: 6.0,
          unit: 'servings',
          meta: [],
          measures: {
            us: {
              amount: 6.0,
              unitShort: 'servings',
              unitLong: 'servings',
            },
            metric: {
              amount: 6.0,
              unitShort: 'servings',
              unitLong: 'servings',
            },
          },
        },
      ],
      id: 634320,
      title: 'Barbecued Pulled Beef Sandwiches',
      readyInMinutes: 45,
      servings: 6,
      sourceUrl:
        'https://www.foodista.com/recipe/6PZJ82YX/barbecued-pulled-beef-sandwiches',
      image: 'https://spoonacular.com/recipeImages/634320-312x231.jpg',
      imageType: 'jpg',
      summary:
        'Barbecued Pulled Beef Sandwiches requires about <b>45 minutes</b> from start to finish. For <b>$2.71 per serving</b>, this recipe <b>covers 26%</b> of your daily requirements of vitamins and minerals. This recipe serves 6. Watching your figure? This dairy free recipe has <b>766 calories</b>, <b>37g of protein</b>, and <b>33g of fat</b> per serving. 5 people were glad they tried this recipe. It works well as a rather inexpensive main course. Head to the store and pick up bacon, hawaiian rolls, olive oil, and a few other things to make it today. It is brought to you by Foodista. All things considered, we decided this recipe <b>deserves a spoonacular score of 53%</b>. This score is pretty good. <a href="https://spoonacular.com/recipes/barbecued-beef-sandwiches-425271">Barbecued Beef Sandwiches</a>, <a href="https://spoonacular.com/recipes/barbecued-beef-sandwiches-425278">Barbecued Beef Sandwiches</a>, and <a href="https://spoonacular.com/recipes/barbecued-beef-sandwiches-425289">Barbecued Beef Sandwiches</a> are very similar to this recipe.',
      cuisines: [],
      dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
      diets: ['dairy free'],
      occasions: [],
      analyzedInstructions: [
        {
          name: '',
          steps: [
            {
              number: 1,
              step: 'Preheat oven to 350 degrees. Line a rimmed cookie sheet with parchment paper.',
              ingredients: [
                {
                  id: 10118192,
                  name: 'cookies',
                  localizedName: 'cookies',
                  image: 'shortbread-cookies.jpg',
                },
              ],
              equipment: [
                {
                  id: 404770,
                  name: 'baking paper',
                  localizedName: 'baking paper',
                  image: 'baking-paper.jpg',
                },
                {
                  id: 404727,
                  name: 'baking sheet',
                  localizedName: 'baking sheet',
                  image: 'baking-sheet.jpg',
                },
                {
                  id: 404784,
                  name: 'oven',
                  localizedName: 'oven',
                  image: 'oven.jpg',
                },
              ],
            },
            {
              number: 2,
              step: 'Lay bacon strips over parchment.',
              ingredients: [
                {
                  id: 10123,
                  name: 'bacon',
                  localizedName: 'bacon',
                  image: 'raw-bacon.png',
                },
              ],
              equipment: [],
            },
            {
              number: 3,
              step: 'Bake pan for 10-15 minutes, or until bacon is crispy.',
              ingredients: [
                {
                  id: 10123,
                  name: 'bacon',
                  localizedName: 'bacon',
                  image: 'raw-bacon.png',
                },
              ],
              equipment: [
                {
                  id: 404784,
                  name: 'oven',
                  localizedName: 'oven',
                  image: 'oven.jpg',
                },
                {
                  id: 404645,
                  name: 'frying pan',
                  localizedName: 'frying pan',
                  image: 'pan.png',
                },
              ],
              length: {
                number: 15,
                unit: 'minutes',
              },
            },
            {
              number: 4,
              step: 'Remove from oven and let cool on pan. Reduce oven heat to 250 degrees and leave oven door open while you dress the beef.',
              ingredients: [
                {
                  id: 23572,
                  name: 'beef',
                  localizedName: 'beef',
                  image: 'beef-cubes-raw.png',
                },
              ],
              equipment: [
                {
                  id: 404784,
                  name: 'oven',
                  localizedName: 'oven',
                  image: 'oven.jpg',
                },
                {
                  id: 404645,
                  name: 'frying pan',
                  localizedName: 'frying pan',
                  image: 'pan.png',
                },
              ],
            },
            {
              number: 5,
              step: 'Drizzle olive oil over the bottom of a medium roasting pan.',
              ingredients: [
                {
                  id: 4053,
                  name: 'olive oil',
                  localizedName: 'olive oil',
                  image: 'olive-oil.jpg',
                },
              ],
              equipment: [
                {
                  id: 404629,
                  name: 'roasting pan',
                  localizedName: 'roasting pan',
                  image: 'roasting-pan.jpg',
                },
              ],
            },
            {
              number: 6,
              step: 'Place meat in roasting pan, and coast with sugar (you want kind of a thin crust). Season generously with salt and pepper and cover with onions. Tent pan with aluminum foil.',
              ingredients: [
                {
                  id: 1102047,
                  name: 'salt and pepper',
                  localizedName: 'salt and pepper',
                  image: 'salt-and-pepper.jpg',
                },
                {
                  id: 11282,
                  name: 'onion',
                  localizedName: 'onion',
                  image: 'brown-onion.png',
                },
                {
                  id: 0,
                  name: 'crust',
                  localizedName: 'crust',
                  image: '',
                },
                {
                  id: 19335,
                  name: 'sugar',
                  localizedName: 'sugar',
                  image: 'sugar-in-bowl.png',
                },
                {
                  id: 1065062,
                  name: 'meat',
                  localizedName: 'meat',
                  image: 'whole-chicken.jpg',
                },
              ],
              equipment: [
                {
                  id: 404765,
                  name: 'aluminum foil',
                  localizedName: 'aluminum foil',
                  image: 'aluminum-foil.png',
                },
                {
                  id: 404629,
                  name: 'roasting pan',
                  localizedName: 'roasting pan',
                  image: 'roasting-pan.jpg',
                },
              ],
            },
            {
              number: 7,
              step: 'Roast meat for 3 to 4-1/2 hours, or until beef is fork tender and can be pulled apart easily.',
              ingredients: [
                {
                  id: 23572,
                  name: 'beef',
                  localizedName: 'beef',
                  image: 'beef-cubes-raw.png',
                },
                {
                  id: 1065062,
                  name: 'meat',
                  localizedName: 'meat',
                  image: 'whole-chicken.jpg',
                },
              ],
              equipment: [],
              length: {
                number: 120,
                unit: 'minutes',
              },
            },
            {
              number: 8,
              step: 'Remove from oven, and set aside to cool slightly. Meanwhile, chop bacon into small-dice bits.',
              ingredients: [
                {
                  id: 10123,
                  name: 'bacon',
                  localizedName: 'bacon',
                  image: 'raw-bacon.png',
                },
              ],
              equipment: [
                {
                  id: 404784,
                  name: 'oven',
                  localizedName: 'oven',
                  image: 'oven.jpg',
                },
              ],
            },
            {
              number: 9,
              step: 'When meat can be handled, shred apart and add barbecue sauce and bacon.',
              ingredients: [
                {
                  id: 6150,
                  name: 'barbecue sauce',
                  localizedName: 'barbecue sauce',
                  image: 'barbecue-sauce.jpg',
                },
                {
                  id: 10123,
                  name: 'bacon',
                  localizedName: 'bacon',
                  image: 'raw-bacon.png',
                },
                {
                  id: 1065062,
                  name: 'meat',
                  localizedName: 'meat',
                  image: 'whole-chicken.jpg',
                },
              ],
              equipment: [],
            },
            {
              number: 10,
              step: 'Mix until evenly coated and bacon is distributed. Season with salt and pepper to taste, and add more barbecue sauce if you will.',
              ingredients: [
                {
                  id: 1102047,
                  name: 'salt and pepper',
                  localizedName: 'salt and pepper',
                  image: 'salt-and-pepper.jpg',
                },
                {
                  id: 6150,
                  name: 'barbecue sauce',
                  localizedName: 'barbecue sauce',
                  image: 'barbecue-sauce.jpg',
                },
                {
                  id: 10123,
                  name: 'bacon',
                  localizedName: 'bacon',
                  image: 'raw-bacon.png',
                },
              ],
              equipment: [],
            },
            {
              number: 11,
              step: 'Serve hot on toasted buns or Hawaiian rolls.',
              ingredients: [
                {
                  id: 98871,
                  name: 'hawaiian roll',
                  localizedName: 'hawaiian roll',
                  image: 'sweet-buns.jpg',
                },
                {
                  id: 0,
                  name: 'roll',
                  localizedName: 'roll',
                  image: 'dinner-yeast-rolls.jpg',
                },
              ],
              equipment: [],
            },
          ],
        },
      ],
      spoonacularSourceUrl:
        'https://spoonacular.com/barbecued-pulled-beef-sandwiches-634320',
      usedIngredientCount: 0,
      missedIngredientCount: 5,
      missedIngredients: [
        {
          id: 10123,
          amount: 6.0,
          unit: 'strips',
          unitLong: 'strips',
          unitShort: 'strips',
          aisle: 'Meat',
          name: 'bacon',
          original: '6 strips bacon',
          originalName: 'bacon',
          meta: [],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/raw-bacon.png',
        },
        {
          id: 13786,
          amount: 2.0,
          unit: 'pounds',
          unitLong: 'pounds',
          unitShort: 'lb',
          aisle: 'Meat',
          name: 'beef chuck',
          original: '2 pounds beef chuck',
          originalName: 'beef chuck',
          meta: [],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/beef-chuck-roast.png',
        },
        {
          id: 11282,
          amount: 1.0,
          unit: '',
          unitLong: '',
          unitShort: '',
          aisle: 'Produce',
          name: 'onion',
          original: '1 onion, chopped',
          originalName: 'onion, chopped',
          meta: ['chopped'],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/brown-onion.png',
        },
        {
          id: 6150,
          amount: 2.0,
          unit: 'cups',
          unitLong: 'cups',
          unitShort: 'cup',
          aisle: 'Condiments',
          name: 'to 3 of barbecue sauce',
          original: '2 cups to 3 of barbecue sauce',
          originalName: 'to 3 of barbecue sauce',
          meta: [],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/barbecue-sauce.jpg',
        },
        {
          id: 18350,
          amount: 6.0,
          unit: 'servings',
          unitLong: 'servings',
          unitShort: 'servings',
          aisle: 'Bakery/Bread',
          name: 'hawaiian rolls',
          original: 'Hamburger buns or Hawaiian rolls',
          originalName: 'Hamburger buns or Hawaiian rolls',
          meta: [],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/hamburger-bun.jpg',
        },
      ],
      likes: 0,
      usedIngredients: [],
      unusedIngredients: [],
    },
    {
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      dairyFree: true,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 22,
      gaps: 'no',
      preparationMinutes: -1,
      cookingMinutes: -1,
      aggregateLikes: 63,
      healthScore: 6,
      creditsText: 'foodista.com',
      sourceName: 'foodista.com',
      pricePerServing: 259.66,
      extendedIngredients: [
        {
          id: 1002030,
          aisle: 'Spices and Seasonings',
          image: 'pepper.jpg',
          consistency: 'SOLID',
          name: 'bell pepper',
          nameClean: 'black pepper',
          original: 'Black pepper',
          originalName: 'Black pepper',
          amount: 2.0,
          unit: 'servings',
          meta: ['black'],
          measures: {
            us: {
              amount: 2.0,
              unitShort: 'servings',
              unitLong: 'servings',
            },
            metric: {
              amount: 2.0,
              unitShort: 'servings',
              unitLong: 'servings',
            },
          },
        },
        {
          id: 18064,
          aisle: 'Bakery/Bread',
          image: 'white-bread.jpg',
          consistency: 'SOLID',
          name: 'bread',
          nameClean: 'bread',
          original: '4 pieces of good quality bread, lightly toasted',
          originalName: 'good quality bread, lightly toasted',
          amount: 4.0,
          unit: 'pieces',
          meta: ['lightly toasted'],
          measures: {
            us: {
              amount: 4.0,
              unitShort: '',
              unitLong: '',
            },
            metric: {
              amount: 4.0,
              unitShort: '',
              unitLong: '',
            },
          },
        },
        {
          id: 11252,
          aisle: 'Produce',
          image: 'iceberg-lettuce.jpg',
          consistency: 'SOLID',
          name: 'lettuce',
          nameClean: 'lettuce',
          original: 'Lettuce',
          originalName: 'Lettuce',
          amount: 2.0,
          unit: 'servings',
          meta: [],
          measures: {
            us: {
              amount: 2.0,
              unitShort: 'servings',
              unitLong: 'servings',
            },
            metric: {
              amount: 2.0,
              unitShort: 'servings',
              unitLong: 'servings',
            },
          },
        },
        {
          id: 4025,
          aisle: 'Condiments',
          image: 'mayonnaise.png',
          consistency: 'LIQUID',
          name: 'mayonnaise',
          nameClean: 'mayonnaise',
          original: 'Mayonnaise',
          originalName: 'Mayonnaise',
          amount: 2.0,
          unit: 'servings',
          meta: [],
          measures: {
            us: {
              amount: 2.0,
              unitShort: 'servings',
              unitLong: 'servings',
            },
            metric: {
              amount: 2.0,
              unitShort: 'servings',
              unitLong: 'servings',
            },
          },
        },
        {
          id: 10310123,
          aisle: 'Meat',
          image: 'raw-bacon.png',
          consistency: 'SOLID',
          name: 'thick- bacon',
          nameClean: 'thick cut bacon',
          original: '8 pieces Thick-sliced bacon',
          originalName: 'Thick-sliced bacon',
          amount: 8.0,
          unit: 'pieces',
          meta: [],
          measures: {
            us: {
              amount: 8.0,
              unitShort: '',
              unitLong: '',
            },
            metric: {
              amount: 8.0,
              unitShort: '',
              unitLong: '',
            },
          },
        },
        {
          id: 11529,
          aisle: 'Produce',
          image: 'tomato.png',
          consistency: 'SOLID',
          name: 'tomato',
          nameClean: 'tomato',
          original: '1 tomato, sliced thin',
          originalName: 'tomato, sliced thin',
          amount: 1.0,
          unit: '',
          meta: ['sliced', 'thin'],
          measures: {
            us: {
              amount: 1.0,
              unitShort: '',
              unitLong: '',
            },
            metric: {
              amount: 1.0,
              unitShort: '',
              unitLong: '',
            },
          },
        },
      ],
      id: 635342,
      title: 'BLT Sandwich',
      readyInMinutes: 45,
      servings: 2,
      sourceUrl: 'http://www.foodista.com/recipe/24R6RD65/blt-sandwich',
      image: 'https://spoonacular.com/recipeImages/635342-312x231.jpg',
      imageType: 'jpg',
      summary:
        'BLT Sandwich might be just the main course you are searching for. One portion of this dish contains approximately <b>20g of protein</b>, <b>60g of fat</b>, and a total of <b>657 calories</b>. This recipe serves 2 and costs $2.6 per serving. 63 people have tried and liked this recipe. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. Head to the store and pick up bell pepper, bread, lettuce, and a few other things to make it today. It is brought to you by Foodista. It is a good option if you\'re following a <b>dairy free</b> diet. With a spoonacular <b>score of 72%</b>, this dish is pretty good. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/blt-sandwich-1363939">BLT Sandwich</a>, <a href="https://spoonacular.com/recipes/best-blt-sandwich-1239867">Best BLT Sandwich</a>, and <a href="https://spoonacular.com/recipes/best-blt-sandwich-492238">Best BLT Sandwich</a>.',
      cuisines: [],
      dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
      diets: ['dairy free'],
      occasions: [],
      analyzedInstructions: [
        {
          name: '',
          steps: [
            {
              number: 1,
              step: 'Brown bacon in a skillet',
              ingredients: [
                {
                  id: 10123,
                  name: 'bacon',
                  localizedName: 'bacon',
                  image: 'raw-bacon.png',
                },
              ],
              equipment: [
                {
                  id: 404645,
                  name: 'frying pan',
                  localizedName: 'frying pan',
                  image: 'pan.png',
                },
              ],
            },
            {
              number: 2,
              step: 'Remove and pat off excess oil',
              ingredients: [
                {
                  id: 4582,
                  name: 'cooking oil',
                  localizedName: 'cooking oil',
                  image: 'vegetable-oil.jpg',
                },
              ],
              equipment: [],
            },
            {
              number: 3,
              step: 'Slice tomato into 1/4 inches slices',
              ingredients: [
                {
                  id: 11529,
                  name: 'tomato',
                  localizedName: 'tomato',
                  image: 'tomato.png',
                },
              ],
              equipment: [],
            },
            {
              number: 4,
              step: 'Toast bread',
              ingredients: [
                {
                  id: 18070,
                  name: 'toast',
                  localizedName: 'toast',
                  image: 'toast',
                },
              ],
              equipment: [],
            },
            {
              number: 5,
              step: 'Spread a thin layer of mayonnaise on bread',
              ingredients: [
                {
                  id: 4025,
                  name: 'mayonnaise',
                  localizedName: 'mayonnaise',
                  image: 'mayonnaise.png',
                },
                {
                  id: 0,
                  name: 'spread',
                  localizedName: 'spread',
                  image: '',
                },
                {
                  id: 18064,
                  name: 'bread',
                  localizedName: 'bread',
                  image: 'white-bread.jpg',
                },
              ],
              equipment: [],
            },
            {
              number: 6,
              step: 'Layer all ingredients on bread and close sandwich',
              ingredients: [
                {
                  id: 18064,
                  name: 'bread',
                  localizedName: 'bread',
                  image: 'white-bread.jpg',
                },
              ],
              equipment: [],
            },
            {
              number: 7,
              step: 'Add fresh cracked black pepper',
              ingredients: [
                {
                  id: 0,
                  name: 'cracked black peppercorns',
                  localizedName: 'cracked black peppercorns',
                  image: 'black-pepper.png',
                },
              ],
              equipment: [],
            },
          ],
        },
      ],
      spoonacularSourceUrl: 'https://spoonacular.com/blt-sandwich-635342',
      usedIngredientCount: 0,
      missedIngredientCount: 5,
      missedIngredients: [
        {
          id: 18064,
          amount: 4.0,
          unit: 'pieces',
          unitLong: '',
          unitShort: '',
          aisle: 'Bakery/Bread',
          name: 'bread',
          original: '4 pieces of good quality bread, lightly toasted',
          originalName: 'good quality bread, lightly toasted',
          meta: ['lightly toasted'],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/white-bread.jpg',
        },
        {
          id: 11252,
          amount: 2.0,
          unit: 'servings',
          unitLong: 'servings',
          unitShort: 'servings',
          aisle: 'Produce',
          name: 'lettuce',
          original: 'Lettuce',
          originalName: 'Lettuce',
          meta: [],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/iceberg-lettuce.jpg',
        },
        {
          id: 4025,
          amount: 2.0,
          unit: 'servings',
          unitLong: 'servings',
          unitShort: 'servings',
          aisle: 'Condiments',
          name: 'mayonnaise',
          original: 'Mayonnaise',
          originalName: 'Mayonnaise',
          meta: [],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/mayonnaise.png',
        },
        {
          id: 10310123,
          amount: 8.0,
          unit: 'pieces',
          unitLong: '',
          unitShort: '',
          aisle: 'Meat',
          name: 'thick- bacon',
          original: '8 pieces Thick-sliced bacon',
          originalName: 'Thick-sliced bacon',
          meta: [],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/raw-bacon.png',
        },
        {
          id: 11529,
          amount: 1.0,
          unit: '',
          unitLong: '',
          unitShort: '',
          aisle: 'Produce',
          name: 'tomato',
          original: '1 tomato, sliced thin',
          originalName: 'tomato, sliced thin',
          meta: ['sliced', 'thin'],
          image: 'https://spoonacular.com/cdn/ingredients_100x100/tomato.png',
        },
      ],
      likes: 0,
      usedIngredients: [],
      unusedIngredients: [],
    },
    {
      vegetarian: true,
      vegan: false,
      glutenFree: true,
      dairyFree: true,
      veryHealthy: true,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 8,
      gaps: 'no',
      preparationMinutes: -1,
      cookingMinutes: -1,
      aggregateLikes: 1,
      healthScore: 6,
      creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
      license: 'CC BY 3.0',
      sourceName: 'Foodista',
      pricePerServing: 154.12,
      extendedIngredients: [
        {
          id: 18413,
          aisle: 'Bakery/Bread',
          image: 'pita-bread.jpg',
          consistency: 'SOLID',
          name: 'pita pockets',
          nameClean: 'pita',
          original: '2 pita pockets',
          originalName: 'pita pockets',
          amount: 2.0,
          unit: '',
          meta: [],
          measures: {
            us: {
              amount: 2.0,
              unitShort: '',
              unitLong: '',
            },
            metric: {
              amount: 2.0,
              unitShort: '',
              unitLong: '',
            },
          },
        },
        {
          id: 10862,
          aisle: 'Meat',
          image: 'cooked-bacon.jpg',
          consistency: 'SOLID',
          name: 'bacon',
          nameClean: 'cooked bacon',
          original: '4 slices cooked bacon',
          originalName: 'cooked bacon',
          amount: 4.0,
          unit: 'slices',
          meta: ['cooked'],
          measures: {
            us: {
              amount: 4.0,
              unitShort: 'slice',
              unitLong: 'slices',
            },
            metric: {
              amount: 4.0,
              unitShort: 'slice',
              unitLong: 'slices',
            },
          },
        },
        {
          id: 10021052,
          aisle: 'Produce',
          image: 'mixed-greens-or-mesclun.jpg',
          consistency: 'SOLID',
          name: 'spring mix greens',
          nameClean: 'spring mix',
          original: '1/2 cup spring mix greens',
          originalName: 'spring mix greens',
          amount: 0.5,
          unit: 'cup',
          meta: [],
          measures: {
            us: {
              amount: 0.5,
              unitShort: 'cups',
              unitLong: 'cups',
            },
            metric: {
              amount: 118.294,
              unitShort: 'ml',
              unitLong: 'milliliters',
            },
          },
        },
        {
          id: 11529,
          aisle: 'Produce',
          image: 'tomato.png',
          consistency: 'SOLID',
          name: 'tomatoes',
          nameClean: 'tomato',
          original: '2 tomatoes, sliced',
          originalName: 'tomatoes, sliced',
          amount: 2.0,
          unit: '',
          meta: ['sliced'],
          measures: {
            us: {
              amount: 2.0,
              unitShort: '',
              unitLong: '',
            },
            metric: {
              amount: 2.0,
              unitShort: '',
              unitLong: '',
            },
          },
        },
        {
          id: 7259,
          aisle: 'Meat',
          image: 'deli-turkey.jpg',
          consistency: 'SOLID',
          name: 'roast turkey',
          nameClean: 'deli turkey',
          original: '4 slices roast turkey',
          originalName: 'roast turkey',
          amount: 4.0,
          unit: 'slices',
          meta: [],
          measures: {
            us: {
              amount: 4.0,
              unitShort: 'slice',
              unitLong: 'slices',
            },
            metric: {
              amount: 4.0,
              unitShort: 'slice',
              unitLong: 'slices',
            },
          },
        },
        {
          id: 4639,
          aisle: 'Oil, Vinegar, Salad Dressing',
          image: 'ranch-dressing.jpg',
          consistency: 'LIQUID',
          name: 'ranch dressing',
          nameClean: 'ranch dressing',
          original: '2 tbsp ranch dressing',
          originalName: 'ranch dressing',
          amount: 2.0,
          unit: 'tbsp',
          meta: [],
          measures: {
            us: {
              amount: 2.0,
              unitShort: 'Tbsps',
              unitLong: 'Tbsps',
            },
            metric: {
              amount: 2.0,
              unitShort: 'Tbsps',
              unitLong: 'Tbsps',
            },
          },
        },
      ],
      id: 1095992,
      title: 'Turkey Ranch BLT',
      readyInMinutes: 10,
      servings: 2,
      sourceUrl: 'https://www.foodista.com/recipe/CQSHG6NN/turkey-ranch-blt',
      image: 'https://spoonacular.com/recipeImages/1095992-312x231.jpg',
      imageType: 'jpg',
      summary:
        'If you have roughly <b>10 minutes</b> to spend in the kitchen, Turkey Ranch BLT might be an awesome <b>dairy free</b> recipe to try. This main course has <b>331 calories</b>, <b>14g of protein</b>, and <b>13g of fat</b> per serving. This recipe serves 2 and costs $1.54 per serving. Head to the store and pick up ranch dressing, bacon, tomatoes, and a few other things to make it today. It is brought to you by Foodista. 1 person were impressed by this recipe. Overall, this recipe earns a <b>solid spoonacular score of 44%</b>. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/blt-ranch-burger-744628">BLT Ranch Burger</a>, <a href="https://spoonacular.com/recipes/blt-ranch-burgers-744632">BLT Ranch Burgers</a>, and <a href="https://spoonacular.com/recipes/blt-ranch-dog-73693">BLT Ranch Dog</a>.',
      cuisines: [],
      dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
      diets: ['dairy free'],
      occasions: [],
      analyzedInstructions: [
        {
          name: '',
          steps: [
            {
              number: 1,
              step: 'Brush the slices of turkey with ranch dressing.Stuff each half of pita with a a few slices of tomato, greens, a slice of turkey, and two slices of bacon.',
              ingredients: [
                {
                  id: 4639,
                  name: 'ranch dressing',
                  localizedName: 'ranch dressing',
                  image: 'ranch-dressing.jpg',
                },
                {
                  id: 21052,
                  name: 'greens',
                  localizedName: 'greens',
                  image: 'mixed-greens-or-mesclun.jpg',
                },
                {
                  id: 11529,
                  name: 'tomato',
                  localizedName: 'tomato',
                  image: 'tomato.png',
                },
                {
                  id: 5165,
                  name: 'whole turkey',
                  localizedName: 'whole turkey',
                  image: 'turkey-raw-whole.jpg',
                },
                {
                  id: 10123,
                  name: 'bacon',
                  localizedName: 'bacon',
                  image: 'raw-bacon.png',
                },
                {
                  id: 18413,
                  name: 'pita',
                  localizedName: 'pita',
                  image: 'pita-bread.jpg',
                },
              ],
              equipment: [],
            },
            {
              number: 2,
              step: 'Serve.',
              ingredients: [],
              equipment: [],
            },
          ],
        },
      ],
      spoonacularSourceUrl: 'https://spoonacular.com/turkey-ranch-blt-1095992',
      usedIngredientCount: 0,
      missedIngredientCount: 6,
      missedIngredients: [
        {
          id: 18413,
          amount: 2.0,
          unit: '',
          unitLong: '',
          unitShort: '',
          aisle: 'Bakery/Bread',
          name: 'pita pockets',
          original: '2 pita pockets',
          originalName: 'pita pockets',
          meta: [],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/pita-bread.jpg',
        },
        {
          id: 10862,
          amount: 4.0,
          unit: 'slices',
          unitLong: 'slices',
          unitShort: 'slice',
          aisle: 'Meat',
          name: 'bacon',
          original: '4 slices cooked bacon',
          originalName: 'cooked bacon',
          meta: ['cooked'],
          extendedName: 'cooked bacon',
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/cooked-bacon.jpg',
        },
        {
          id: 10021052,
          amount: 0.5,
          unit: 'cup',
          unitLong: 'cups',
          unitShort: 'cup',
          aisle: 'Produce',
          name: 'spring mix greens',
          original: '1/2 cup spring mix greens',
          originalName: 'spring mix greens',
          meta: [],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/mixed-greens-or-mesclun.jpg',
        },
        {
          id: 11529,
          amount: 2.0,
          unit: '',
          unitLong: '',
          unitShort: '',
          aisle: 'Produce',
          name: 'tomatoes',
          original: '2 tomatoes, sliced',
          originalName: 'tomatoes, sliced',
          meta: ['sliced'],
          image: 'https://spoonacular.com/cdn/ingredients_100x100/tomato.png',
        },
        {
          id: 7259,
          amount: 4.0,
          unit: 'slices',
          unitLong: 'slices',
          unitShort: 'slice',
          aisle: 'Meat',
          name: 'roast turkey',
          original: '4 slices roast turkey',
          originalName: 'roast turkey',
          meta: [],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/deli-turkey.jpg',
        },
        {
          id: 4639,
          amount: 2.0,
          unit: 'tbsp',
          unitLong: 'tablespoons',
          unitShort: 'Tbsp',
          aisle: 'Oil, Vinegar, Salad Dressing',
          name: 'ranch dressing',
          original: '2 tbsp ranch dressing',
          originalName: 'ranch dressing',
          meta: [],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/ranch-dressing.jpg',
        },
      ],
      likes: 0,
      usedIngredients: [],
      unusedIngredients: [],
    },
  ],
  offset: 0,
  number: 5,
  totalResults: 15,
};
